PharmaTechVe/pharmatech-sdk

.github/workflows/cd.yml
README.md
package.json
src/tests/api.test.ts

- Se configuro el proyecto como una libreria
- Se agrego vitest para las pruebas unitarias
- Se agrego husky para el pre-commit y el pre-push
- Se creo el paquete en npm

API-5: setup sdk repository

---

package-lock.json
src/auth.ts
src/tests/api.test.ts

1 ) Agregando el sdk de sign up
2 ) Agregando los test correspondientes de sign up

feat API-8: add sign up sdk and sign up test

---

src/auth.ts
src/tests/api.test.ts

SignUpRequest en phone y gender acepta ahora como respuesta null

Fix(API-24-SDK): SignUpRequest on phone and gender accepts null

---

package.json
src/auth.ts
src/index.ts
src/tests/api.test.ts

- Update optional properties in signup
- Add validateOtp method

Release 0.2.1

---

package-lock.json
src/index.ts
src/tests/api.test.ts
src/user.ts

Agregando dos endpoints al sdk, obtener perfil, y obtener lista de usuarios.

Feature: Adding getProfile and getUsers to the SDK

---

package.json
src/index.ts
src/tests/api.test.ts
src/user-address.ts

This pull request includes a version update for the PharmaTech SDK and modifications to the `UserAddressService` class to include JWT authentication. The most important changes are listed below:
Version update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the SDK version from `0.3.2` to `0.3.3`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L64-R64): Updated the `version` method in the `PharmaTech` class to return `0.3.3`.
* [`src/tests/api.test.ts`](diffhunk://#diff-e42a6be310013b3ec0ba290849ab6164324e4c967a08df189fb30fa9c52309eaL28-R28): Updated the test to check for the new version `0.3.3`.
JWT authentication:
* …

Release 0.3.3

---

package.json
src/generic-product.ts
src/index.ts
src/product-image.ts
src/product-presentation.ts
src/tests/api.test.ts

This pull request includes several updates to the PharmaTech SDK, including version updates, new services, and additional type definitions. The most important changes are summarized below:
* Updated the SDK version from `0.3.3` to `0.3.4` in `package.json` and `PharmaTech.version()` method. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L64-R70) [[3]](diffhunk://#diff-e42a6be310013b3ec0ba290849ab6164324e4c967a08df189fb30fa9c52309eaL28-R28)
* Added `ProductPresentationService` and `ProductImageService` to the `PharmaTech` class. [[1]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R16-R17) …

Release 0.3.4

---

package.json
src/index.ts
src/product.ts
src/tests/api.test.ts

This pull request includes updates to the versioning of the PharmaTech SDK, enhancements to the `ProductService`, and corresponding test updates. The most important changes include updating the version number, adding new request parameters to `ProductService`, and modifying the tests to reflect the version change.
Versioning updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `0.3.4` to `0.3.5`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L70-R70): Updated the `version` method to return `0.3.5` instead of `0.3.4`.
Enhancements to `ProductService`:
* [`src/product.ts`](diffhunk://#diff-5a2501e34f80b8359b9ff967db751a9fbddf78cf1bf9ee9268aff3cb81005b …

Release 0.3.5

---

package.json
src/index.ts
src/tests/api.test.ts
src/user.ts

This pull request includes several changes to the PharmaTech SDK, focusing on version updates, user management enhancements, and test adjustments. The most important changes are summarized below:
Version Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `0.3.5` to `0.3.6`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L70-R70): Updated the `version` method to return `0.3.6` instead of `0.3.5`.
* [`src/tests/api.test.ts`](diffhunk://#diff-e42a6be310013b3ec0ba290849ab6164324e4c967a08df189fb30fa9c52309eaL28-R28): Updated the test to expect the version `0.3.6` instead of `0.3.5`.
User Management Enhancements:
* …

Release 0.3.6

---

package.json
src/index.ts
src/tests/api.test.ts

This pull request includes a version update for the PharmaTech SDK and some changes to the `PharmaTech` class in the `src/index.ts` file. The most important changes are:
Version update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version of the PharmaTech SDK from `0.3.6` to `0.3.7`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L70-R70): Updated the `version` method to return `0.3.7` instead of `0.3.6`.
* [`src/tests/api.test.ts`](diffhunk://#diff-e42a6be310013b3ec0ba290849ab6164324e4c967a08df189fb30fa9c52309eaL28-R28): Updated the test case to check for version `0.3.7` instead of `0.3.6`.
Changes to `PharmaTech` class:
* …

Release 0.3.7

---

README.md
package.json
src/auth.ts
src/index.ts
src/tests/api.test.ts
src/user-address.ts

This pull request includes several changes across multiple files to add new features, update versioning, and improve the codebase. The most important changes include the addition of a new method in the `AuthService` class, updating the version number, and extending the `UserAddressResponse` and `createAddresData` types with new fields.
* [`src/auth.ts`](diffhunk://#diff-84a5d130fb4cccb80f78601d140f1d5397dc0272f94cea672a8470539fcf6dc7R110-R124): Added `updateCurrentPassword` method to the `AuthService` class to allow users to update their current password.
* [`src/auth.ts`](diffhunk://#diff-84a5d130fb4cccb80f78601d140f1d5397dc0272f94cea672a8470539fcf6dc7R53): Bound the new `updateCurrentPassword` method in the constructor.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427 …

Release 0.3.10

---

src/index.ts
src/services/index.ts
src/services/profile-delivery.ts
src/services/user-address.ts
src/types/index.ts
src/types/profile-delivery.ts

Sdk del profile delivery
(Tambien aproveche hacer en fix en direcciones de usuario, el actualizar)

Feat(API-45): profile-delivery-sdk

---

src/types/delivery.ts

Solving delivery response (types)

---

package.json
src/index.ts
src/services/product.ts
src/types/delivery.ts
src/types/order.ts
src/types/product.ts

This pull request introduces a version bump for the PharmaTech SDK, extends functionality in the `ProductService` class, and adds new types and properties to enhance the delivery and order management features. Below is a summary of the most important changes:
* Updated the SDK version from `0.4.5` to `0.4.6` in `package.json` and the `version` method of the `PharmaTech` class to reflect the new release. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L97-R97)
* Added support for filtering by `genericProductId` in the `ProductService` class by updating the `ProductPaginationRequest` type and corresponding query parameters. …

Release 0.4.6

---

src/types/delivery.ts

**Agregando el campo address a la respuesta AddressOrderDeliveryDetailResponse, agregando los campos de control al orderDeliveryResponse**, 
vista de todo el type delivery:

Hotfix(API-42)

---

package.json
src/index.ts
src/services/delivery.ts
src/services/order.ts
src/types/delivery.ts

This pull request introduces several updates to the PharmaTech SDK, including a version bump, enhancements to the `DeliveryService` and `OrderService` classes, and improvements to type definitions. The most significant changes involve adding support for JWT authentication in service methods and updating type definitions for better consistency and usability.
* Updated the SDK version from `0.4.6` to `0.4.7` in `package.json` and the `version()` method in `PharmaTech` class. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L97-R97)
* Modified `DeliveryService` methods (`getById` and `findAll`) to accept a `jwt` parameter for authentication.
* Updated …

Release 0.4.7

---

package.json
src/index.ts
src/types/delivery.ts

This pull request updates the SDK version and introduces enhancements to the delivery-related types in the codebase. The most important changes include updating the version in both `package.json` and the `PharmaTech` class, and extending delivery-related response types with additional fields.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the SDK version from `0.4.8` to `0.4.9`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L97-R97): Updated the `version()` method in the `PharmaTech` class to return `0.4.9`.
* [`src/types/delivery.ts`](diffhunk://#diff-9f808bce50e73e6a27556daa84c1faec431bbb5e3c5b129261594b0b9c16886dR24-R34): Added `email` and `profilePicture` fields …

Release 0.4.9

---

package.json
src/index.ts
src/services/payment-information.ts

This pull request includes a version bump for the PharmaTech SDK, along with a type update for the `findAll` method in the `PaymentInformationService` class to return an array. These changes ensure consistency in versioning and improve type accuracy for the `findAll` method.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the SDK version from `0.4.12` to `0.4.13`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L105-R105): Updated the `version()` method in the `PharmaTech` class to return `0.4.13`.
* [`src/services/payment-information.ts`](diffhunk://#diff-ad27cb6a0f5e7a506b50f6427215a76b04b371a186ddebbc213ce758f6f6a496L29-R34): Changed the return type of the `findAll` …

Release 0.4.13

---

package.json
src/index.ts
src/services/payment-information.ts
src/services/product.ts
src/types/order.ts
src/types/payment-confirmation.ts
src/types/product.ts

This pull request includes updates to the PharmaTech SDK version, enhancements to the `ProductService` and `Order` types, and cleanup of unused imports. Below is a summary of the most important changes:
* Updated the SDK version in `package.json` and the `version()` method in `src/index.ts` from `0.4.14` to `0.4.15`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L105-R105)
* Added support for filtering products by `id` in `ProductPaginationRequest` and updated the `ProductService` to include the `id` parameter in API requests. [[1]](diffhunk://#diff-fd2cfb4624ef03c94fb2a09c00a2b915e25e8c59c61381c994178e0773813b90R27) …

Release 0.4.15

---

package.json
src/index.ts
src/services/inventory.ts
src/types/inventory.ts

This pull request introduces a new feature for bulk updating inventory in the PharmaTech SDK, along with minor version updates. The most important changes include adding a `bulkUpdate` method to the `InventoryService` class, defining new types to support bulk updates, and updating the package version.
* [`src/services/inventory.ts`](diffhunk://#diff-4617241c2e0bbeb4644b3d5a1b8dddc5b42b17de0eba5de3db34c28c87fe9af7R64-R75): Added a new `bulkUpdate` method to the `InventoryService` class, allowing users to update multiple inventory items in bulk by sending a request to the `/inventory/bulk` endpoint.
* [`src/types/inventory.ts`](diffhunk://#diff-fb2bc1571a5c982b0d4afeecf962eb62ac8f2175e15ffad874a0ece4b134daf1R21-R30): Introduced new types `InventoryBulkDetail` and `UpdateInventoryBulk` to …

Release 0.4.16

---

package.json
src/index.ts
src/services/coupon.ts
src/services/order.ts
src/services/product-presentation.ts
src/services/promo.ts
src/services/user.ts
src/types/coupon.ts
src/types/order.ts
src/types/product-presentation.ts
src/types/promo.ts
src/types/user.ts

This pull request introduces a version bump for the PharmaTech SDK and adds bulk operations for several services, including coupons, orders, product presentations, promos, and users. It also includes updates to their respective types to support these new operations.
* Updated the SDK version from `0.4.17` to `0.4.18` in `package.json` and the `version()` method in `src/index.ts`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L111-R111)
* Added `bulkUpdate` and `bulkDelete` methods to `CouponService` for handling bulk operations. [[1]](diffhunk://#diff-871528080ba90759fc5ec832ba0a930b48cdda2c028b57ebafe59e50c3e53cfdR21-R22) …

Release 0.4.18

---

package.json
src/client.ts
src/index.ts

This pull request includes a version bump for the PharmaTech SDK and a minor update to the `Client` class to clear request interceptors before processing a request. Below is a summary of the most important changes:
* Updated the SDK version from `0.4.19` to `0.4.20` in `package.json` and the `version()` method in `src/index.ts` to reflect the new release. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L111-R111)
* Added a call to `this.client.interceptors.request.clear()` in the `Client` class (`src/client.ts`) to ensure that request interceptors are cleared before making a new request, improving reliability.

Release 0.4.20
